styled-components/jest-styled-components

index.d.ts
package.json
test/index.spec.js
yarn.lock

This fixes #18.
I've also added a npm script `test-ts` to check if typings are okay. It simply runs the Typescript compiler with `test/index.spec.ts` and should not throw during the compilation.
Obviously it's not necessary to support Typescript, so I can remove it if you don't want "Typescript stuff" in the project, other than the minimal configs to support it.

chore: add Typescript typings

---

src/index.js
src/matchers/toHaveStyleRule.js
src/serializers/styleSheetSerializer.js
src/utils.js
test/index.spec.js

Based on my [previous PR](https://github.com/styled-components/jest-styled-components/pull/24).
Basically now just reads the stylesheet CSS the "v2 way" (I created a reusable function for reading the css on different styled-components versions). Didn't test the native version of `toHaveStyleRule` so it might just be that it still needs a bit of work.
https://github.com/styled-components/jest-styled-components/pull/14#issuecomment-306690511

v2 compatible version of toHaveStyleRule

---

src/serializers/styleSheetSerializer.js
src/utils.js
test/utils.spec.js

It might be hard to tell in the diff, this is the line that changed:
`acc.concat(getClassNames(child, []))`
I thought of another solution that uses `push` instead of `concat` to save memory, not sure if it's necessary though... so I'll just open this PR for meow
EDIT:
This was happening until I made the change in this PR
```
FAIL  ./storyshots.test.js (10.358s)
● Storyshots › ReactSwagger › default
RangeError: Invalid array length
at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:22:18)
at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:147:25)
at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
at process._tickCallback (internal/process/next_tick.js:109:7)
● Storyshots › ReactSwagger › no title
RangeError: Invalid array …
```

Performance improvement getClassNames

---

README.md

@MicheleBertoli I took your comments from the issue and added it to the README https://github.com/styled-components/jest-styled-components/issues/33

Add bare minimum documentation

---

src/utils.js

You can see an example of how to reproduce the bug here: https://github.com/wongterrencew/jest-styled-components-storybook-example/pull/1
Fixing this will be helpful for people transitioning to `styled-components` but still have some other components styled with other tools :)

fix: was throwing exception when testing a component not using SC

---

src/utils.js
test/utils.spec.js

Hello, it's me :)
Unfortunately I can't show the example I have of this bug with actual components (it's in a closed source project) and it's not super trivial to replicate.
When parsing the styles from the html if there were multiple style tags, the regex would capture
everything between the first opening <style> tag and the last closing
</style> tag
Because of this I was getting the following error:
```
● Storyshots › Button › default
undefined:1:97: missing '{'
at Object.styledSnapshot [as test]
(src/components/storyshots.spec.js:10:16)
at Object.<anonymous>
(node_modules/@storybook/addon-storyshots/dist/index.js:147:25)
at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
```
EDIT: I got the regex by adapting it from this stack overflow post: …

fix: support html with multiple style tags

---

README.md
src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

@MicheleBertoli 
As to https://github.com/styled-components/jest-styled-components/issues/52
Enhancements to support media queries rules is here. I tried to use less code as possible :grinning:. Don't know if you have better patterns on checking the options (I don't know if you like using objects to define functions to handle or else :joy:). For now it looks clean, but if other more options (like finding rules for ```:hover``` as mentioned further in the issue is implemented. 
Also using options as mention earlier like ```{ media: { 'max-width': '768px' } }``` may not be easy. It requires more work, I read the css parser docs and it doesn't parse the media syntax :joy:. So maybe right now just use simple strings to match media rules, because it could easily support multiple rules too like …

Test style rules with media queries options

---

src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

@MicheleBertoli I manage to get it done with your help for the hasClassNames function. Thanks 😃 
- When getting rules, it needs to distinguish whether the options includes a At rule or not. I added a ```hasAtRule``` function for checking (Not known if this should be in utils.js?). The array containing at rules value should be easily added for checking, but right now can we just keep it simple? (I think most users would be using media rules. 😂 )
- Letting the user to pass colon symbols in the pseudo option makes it dynamically for users that like single, or double colons.
- Now, we can accomplish combinations At rules and pseudo selectors. 👍 
- I have to take back the option default as empty object as undefined will break at ```hasAtRule``` function

Pseudo selectors support

---

README.md

`styled-component` has a community on Spectrum, so I made a Jest channel and added a link to it to the README

Add link to chatroom to README

---

src/toHaveStyleRule.js
test/__snapshots__/toHaveStyleRule.spec.js.snap
test/toHaveStyleRule.spec.js

Jest 21.0.0 and above expect `result.message` to be a function.
See https://github.com/facebook/jest/pull/3972 (commit facebook/jest@b3d944e)

Jest 21.0.0 compatibility: Make message in matchers a function

---

package.json
src/styleSheetSerializer.js
test/__mocks__/requestAnimationFrame.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/jest.setup.js
yarn.lock

I upgraded my codebase to React 16 and this library stopped outputting styles. The issue seems to be that the nodes returned by `getNodes` have the prop `class` rather than `className`.
If you don't want to upgrade this whole library to React 16 just yet, you can cherry pick 799d1a7, which fixes the issue but doesn't update the dependencies or snapshots.

Update to work with React 16

---

src/native/toHaveStyleRule.js

Closes https://github.com/styled-components/jest-styled-components/issues/76
Hi @MicheleBertoli!
So, I finally got some time to work on #76 🙂 After talking a look on list of changes, I decided to rewrite the matcher. Previously, it was parsing given AST etc, but now, with the new version, it doesn't seem to be needed (:tada:). 
As far as we get all styles pre-calculated, their names are converted to camelCase. In order to keep the matcher signature (and make transition painless), I convert given kebab-case names to camelCase under the hood. 
Besides that, from now on we can't use component names (so instead of fancy `Foo` component, it'll give back `View`).
---
Anyway, I hope you like the PR and it'll be a good improvement to existing codebase ;)

Rewrite toHaveStyleRule for React Native

---

test/native/__snapshots__/toHaveStyleRule.spec.js.snap
test/native/toHaveStyleRule.spec.js
yarn.lock

Hi @MicheleBertoli!
As I promised, I added (just adapted existing ones tbh) a few new `toHaveStyleRule`-related tests. Thanks to these tests, I found out that some functionality like regexp matching, expecting null and some style name mismatching (`background` translates to `backgroundColor` in React Native) is not covered in the code. I'll follow up on this in the following PRs. At least, now we know that the issue exists. I disabled failing tests and will re-enable them once missing functionality is there.

Add new native tests

---

README.md
package.json
src/utils.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/toHaveStyleRule.spec.js
test/utils.spec.js
yarn.lock

Fix #112
This uses the new secret internals that were added in styled-components@3.0.2, since the new v3 versions now use flat bundles and don't expose the `lib/` folder at all.
@MicheleBertoli There are some failing tests which I'm not sure about. Didn't know how to fix them but I think they might be related to an upgrade of stylis?

Upgrade to styled-components v3 and use secret internals

---

README.md
src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

There are 2 commits in this PR as discussed in this issue https://github.com/styled-components/jest-styled-components/issues/64
1. Updates the existing modifier syntax to remove the need to add a starting space. Also adds support for more complex modifiers
2. Updates the modifier syntax to accept child Styled Components by passing in an array of strings and styled components, interpolating them into a final string modifier.
I'm open to discussion about the 2nd one, since that's a pretty ugly looking array. Im not sure how else to support nested components without requiring testers to know about the `styledComponentId` property. If we're otherwise ok with this modification, I can go ahead and update the docs as well.
An alternative I've been thinking of could be something like:
```js …
```

Add better support for various modifiers

---

README.md

One tiny grammatical fix and highlighting the `modifier` option for clarity.

Fixing a couple of things in the readme

---

README.md

Updating README per discussion in https://github.com/styled-components/jest-styled-components/issues/106 to include a full DOM rendering example when using enzyme.
@MicheleBertoli lemme know if I should format this differently. Was considering merging the shallow and deep examples together to make it DRY-er but I figured keeping them separate would make the code clearer. Up for suggestions though!

Added full dom rendering example in README for themes with enzyme

---

README.md

Added an FAQ section that outlines why Jest Styled Components might not be working.

Update README.md (fixes #125)

---

README.md
src/styleSheetSerializer.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/preact/__snapshots__/styleSheetSerializer.spec.js.snap

**Note this is a breaking change.**
This change implements the enhancement issue "Please consider wrapping the added style string in <style> element #135". 
**Problem**:  The styles added to the snapshot by _jest-styled-components_ are not added as valid HTML. Therefore _jest-html_ can not render the HTML with the added styles. 
**Solution**: Then the styles are added to the snapshot, add then in a `<style>` element. 
It would have been nice to be able to implement this change in a backward compatible way, where the feature is enabled by an configuration object injected when the module is imported. However, due to the unusual way the _serializer_ is added this does not seem possible.
Since this is a breaking change any existing tests must be successfully tested with a previous version …

Styles are added to the snapshot as valid HTML in the <style> element.

---

src/toHaveStyleRule.js
src/utils.js
test/toHaveStyleRule.spec.js

Hey @MicheleBertoli,
I'm back with a new PR, once this is merged I will also raise another one to address eslint/prettier formatting clashes.
The matching logic has recently been refactored using jest `toEqual` in order to support `undefined` and jest asymmetric matchers in addition to strings and regexp as part of #148.
For strings and regexp #148 introduced comparison with the asymmetric matcher `stringMatching` which, according to the documentation, supports strings and regexp but this matcher actually transforms strings into regexp.
This creates issues with complex strings like `'1px solid rgba(0,0,0,.125)'` which gets transformed into `/1px solid rgba(0,0,0,.125)/`.
In this case a test like this would always fail
```js
// Pure jest example
expect('1px solid …
```

Fix matcher logic to work with complex strings

---

.eslintrc
package.json
src/toHaveStyleRule.js

This project is using ESlint as linting utility and Prettier for code formatting.
ESlint is an advanced linting tool that also include a number of formatting rules.
The entire reasons behind Prettier is to be opinionated about code formatting.
In some complex cases (e.g. inline ternaries) the two tools will actually conflict with each other as they have different requirements about code formatting.
When it comes to code formatting we need a single source of truth to deal consistently with formatting styles; since Prettier job is exactly to care about code formatting its rules must be given precedence.
I have introduced the `eslint-config-prettier` dependency that allows ESLint not to complain about formatting "issues" which are simply a different preference than what Prettier does.
The …

Use Prettier as single source of truth for formatting rules

---

package.json
serializer/index.js

Hello,
I would like to integrate `jest-styled-components` with `jest-specific-snapshot`. Unfortunately, serializers are added differently in this case. We must use a function `addSerializer` from package `jest-specific-snapshot`, but I can not do it because class `styleSheetSerializer` is private.
Thanks in advance.

Export styleSheetSerializer, toHaveStyleRule

---

src/utils.js
test/utils.spec.js

As already mentioned in #169 there is an attribute update in v4 of styled-components.

Updated regex to match attribute change of v4

---

src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

The `mediaRegex` is responsible for normalising media queries to be matched against CSS rules.
When defining a CSS rule like `@media (min-width: 576px) { ... }` this gets transformed to `@media screen and (min-width:576px)` (note the missing space after the colon); these rules can be tested with `toHaveStyleRule` by adding the following key-value to the options object `{ media: '(min-width: 576px)' }` and the `mediaRegex` will transform this at-rule into `(min-width:576px)` so that it can match the rule attached to the component.
This doesn't work with decimal values as the regex takes into consideration only letters after the colon.
Decimal values are fully valid and commonly used (even by [bootstrap)](https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints) to avoid …

Fix mediaRegex to allow dot special character

---

src/toHaveStyleRule.js

Remove object rest/spread notation to continue Node 6 support

---

README.md
src/native/toHaveStyleRule.js
src/toHaveStyleRule.js
test/native/toHaveStyleRule.spec.js
test/toHaveStyleRule.spec.js

Following the input from #205 I'm creating this PR to add a feature to `toHaveStyleRule` to be able to work with a negated ".not" modifier and a not passed expected value to allow the following syntax:
```
expect(<Component />).not.toHaveStyleRule('opacity')
```
Key-points:
1. No breaking changes
2. Purely additive, doesn't revisit any existing behaviour
3. It supports both React and React-Native
4. Tests for this new use case are added for both web and native
5. The Readme has been updated to document the use of this new feature
I know the work on this project is currently focused around compatibility with SCv4, however this should be merged on existing master and be followed by an new npm release.
This will not only allow existing users to benefit from this feature even before SCv4 work …

 toHaveStyleRule to work with not passed expected value and negated ".not" modifier

---

src/native/toHaveStyleRule.js
src/toHaveStyleRule.js
test/native/toHaveStyleRule.spec.js
test/toHaveStyleRule.spec.js
typings/index.d.ts

Hey @MicheleBertoli,
quick PR to fix a small edge case introduced in #206.
This is to fix a scenario which would cause the following test to fail when it shouldn't
```javascript
const Button = styled.button`
opacity: .65;
`
expect(<Button />).not.toHaveStyleRule('opacity', undefined)
```
Since the `opacity` rule is applied to `Button` we can also write a test to check that the rule should not be undefined.
I consider this an edge case since this test is certainly convoluted and possibly pointless as most likely if you have a rule applied you want to write a test to check its value.
When the requested rule is undefined and the expected value is not passed or falsy and the negated `.not` modifier is used then we can return directly `false` to make our test pass without any need to use the …

Fix negated ".not" modifier usage edge case

---

.jest.preact.json
package.json
src/index.js
src/styleSheetSerializer.js
src/utils.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/native/toHaveStyleRule.spec.js
test/preact/__snapshots__/styleSheetSerializer.spec.js.snap
test/preact/setup.js
test/preact/styleSheetSerializer.spec.js
test/preact/toHaveStyleRule.spec.js
test/setup.js
test/styleSheetSerializer.spec.js
test/toHaveStyleRule.spec.js
test/utils.spec.js
yarn.lock

haven't managed to get the preact ones to work yet... doesn't
seem like preact 10 is ready enough yet and for preact-compat the
createContext implementation is actually in a separate package
so not sure how to fake it being part of preact-compat

[breaking] v5 support

---

README.md

`setupTestFrameworkScriptFile` is now `setupFilesAfterEnv`. https://jestjs.io/docs/en/configuration#setupfilesafterenv-array

Update Global installation instructions

---

typings/index.d.ts

the `Matchers` type of definitelytyped's jest package have been updated (see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L639 ), which causes a compilation error since the interfaces don't match anymore.
See: https://github.com/FormidableLabs/enzyme-matchers/issues/318 or https://github.com/testing-library/jest-dom/issues/152
This PR changes the type to match the new one.

Update Matchers interface

---

README.md

The global installation section is outdated.
I saw the issue already open but no one addressed it so far.
https://github.com/styled-components/jest-styled-components/issues/237
Instructions fix is quite easy because when following these instructions, the error message will show displaying this message: 
`We detected setupFilesAfterEnv in your package.json. Remove it from Jest configuration, and put the initialization code in src/setupTests.js. This file will be loaded automatically.`

Edited readme file to update global installation section

---

src/native/toHaveStyleRule.js

replace object spread with object.assing to have support for the current node LTS versions (10/12) and avoid errors like `SyntaxError: Unexpected token ...`

Remove object spread to continue Node LTS 10/12 support

---

src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

Fixes `toHaveStyleRule` support for classes with a `displayName` prefix from  babel-plugin-styled-components
Closes #290 #294

Fix toHaveStyleRule support classes with displayName prefix

---

src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

Fix issue introduced in #309, the .find is broken when try to
get/check styles in children components if the component have another className.
e.g.
```javascript
const ParentComponent = (props) => (
<MyStyledComponent {...props}>
<Children className="test-class" /> //--> it don't get styled class
<Children /> //--> it get styled class
</MyStyledComponent>
);
```
also in mount for parent
```javascript
<MyStyledComponent className="test-class" />
```
Also `node.props("className").className` is not necessary and redundant coz `node.prop("className");` return the same in mount/shallow

Fix get styled className from children components

---

src/styleSheetSerializer.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/styleSheetSerializer.spec.js

Due to changes in styled-components v5, certain hashed class names are no longer being included in masterSheet, and therefore are not being serialized in snapshots by jest-styled-components.
Specifically, this occurs in the case where a styled component (`StyledDiv`) refers to another styled component (`StyledDiv = styled(BaseDiv)`) and the base component (`BaseDiv`) is not referenced in the component tree.
This PR proposes stripping all static `sc-` prefixed classes from snapshot results as a brute force way to resolve this issue.
Relevant styled-components doc:
https://styled-components.com/docs/advanced#referring-to-other-components
Relevant issues:
https://github.com/styled-components/jest-styled-components/issues/307
https://github.com/styled-components/jest-styled-components/issues/2 …

Strip static class names from jest snapshot results

---

src/styleSheetSerializer.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/styleSheetSerializer.spec.js

This PR removes CSS rules referencing unused styled components from the snapshot. See #350 for details.
The approach I took here was adding a filter for CSS rules which contain references to unknown styled component class names.
Note that this also fixes a test; "referring to other components", which was incorrectly passing, as it contained a reference to a container element that was never used.

Fix #350 - Strip styled components referenced in css by not used in the render

---

src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

The mediaQueryRegex does not replace the space after `:` if the media query has a calc, because the second capture group doesn't match it. E.g.  for `(max-width: calc(100px + 1px))` the space is not replaced, so `toHaveStyle` doesn't find the query.
I think this regex should only be concerned with the `: ` situation, instead of matching all possible media queries. Then it wouldn't need fixes like #182.
I've also removed unnecessary eslint-disable prettier/prettier comments.

Simplify media query regex for removing spaces

---

src/utils.js
test/utils.spec.js

On cleanup, `jest-styled-components` resets `styled-components` internal state, but leaves styles in document head. This leads to significant jsdom performance degradation in large tests.
This PR improves cleanup, so that `style[data-styled-version]` nodes are removed from the document.

Remove sc style nodes on cleanup

---

package.json
typings/index.d.ts
yarn.lock

Fix type error with `modifier`

---

src/styleSheetSerializer.js
test/__snapshots__/styleSheetSerializer.spec.js.snap
test/styleSheetSerializer.spec.js

After the first render the node are marked with KEY property.
Calling the rerender function of RTL the nodes remain marked and the print function will never call again.

Fix issue #317

---

src/native/toHaveStyleRule.js
src/toHaveStyleRule.js
src/utils.js
test/native/toHaveStyleRule.spec.js
test/toHaveStyleRule.spec.js

Closes https://github.com/styled-components/jest-styled-components/issues/344

fix: incorrect negated assertion for rule existence check

---

package.json
src/styleSheetSerializer.js
src/utils.js
yarn.lock

The package `css` is not maintained anymore.
More, it has a dependency on https://www.npmjs.com/package/source-map-resolve which is deprecated (and contain CVE if I remember correctly)
The new package `@adobe/css-tools` is a fork of `css` without the source-map support and with some optimization and typescript support. It also fixes few smalls issues and I belive that one of them is: https://github.com/styled-components/jest-styled-components/pull/356

Use @adobe/css-tools (maintained) instead of css (unmaintained)

---

src/utils.js

Currently this loop calls getHTML() on each cycle, when the value doesn't or shouldn't change. This extracts it to a separate variable so it's only called once.

perf(utils): only extract HTML once during while loop

---

src/toHaveStyleRule.js
test/toHaveStyleRule.spec.js

Fixes #403 by extending the regex for the `isStyledClass` function to support look for the patterns `-sc-`or `_sc-` anywhere in a class name or `sc-` at the start of class name. This should allow toHaveStyleRule to function with classNames that contain a filename for a component within them even when that filename is snake case.

Fix issue #403 with snake case filenames

---

package.json
src/styleSheetSerializer.js
test/styleSheetSerializer.spec.js
typings/index.d.ts
yarn.lock

This fixes #355 and is just #356 rebased against current main. It was a pretty straightforward rebase, just required updating the class names manually.

Fix diff on unchanged
